### ISSUE TITLE
The number of discriminator categories is 89, but the output shape is torch.Size([1, 267]), is there any problem?

### ISSUE THREAD

**Issue by 980202006** [XXxin1/tpse-vc#1]
The number of discriminator categories is 89, but the output shape is torch.Size([1, 267]), is there any problem?

**Comment by XXxin1** [comment]
Sorry for the delay, in our work,  when we use the discriminator, we set the parameter 'classify' to False.  Thus, the number of discriminator categories doesn't work, and we don't use classification loss in the training stage.
